apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "0e42dc57-73b8-4298-a290-82d249b809a9"
  labels:
    azure.workload.identity/use: "true"
  name: accessapp1
  namespace: accessapp1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "bd876ba9-46d6-4a24-9b82-5bf67536828f"
  name: accessapp2
  namespace: accessapp2