# This is a SecretProviderClass example using workload identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi # needs to be unique per namespace
  namespace: accessapp1
spec:
  provider: azure
  secretObjects:  # list of secret objects
    - secretName: accessapp1-secret  # name of the secret in the pod
      type: Opaque
      data:
        - objectName: ExampleSecret             # name of the secret in the key vault
          key: ExampleSecret                    # object types: secret, key, or cert
        - objectName: ExampleSecret1             # name of the secret in the key vault
          key: ExampleSecret1                    # object types: secret, key, or cert
  parameters:
    usePodIdentity: "false"
    clientID: "0e42dc57-73b8-4298-a290-82d249b809a9" # Setting this to use workload identity
    keyvaultName: accessapp1vault      # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ExampleSecret             # Set to the name of your secret
          objectType: secret                    # object types: secret, key, or cert
          objectVersion: ""                     # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: ExampleSecret1                # Set to the name of your key
          objectType: secret
          objectVersion: ""
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"        # The tenant ID of the key vault
---
# This is a SecretProviderClass example using workload identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi # needs to be unique per namespace
  namespace: accessapp2
spec:
  provider: azure
  secretObjects:  # list of secret objects
    - secretName: accessapp2-secret  # name of the secret in the pod
      type: Opaque
      data:
        - objectName: ExampleSecret             # name of the secret in the key vault
          key: ExampleSecret                    # object types: secret, key, or cert
        - objectName: ExampleSecret1             # name of the secret in the key vault
          key: ExampleSecret1                    # object types: secret, key, or cert
  parameters:
    usePodIdentity: "false"
    clientID: "bd876ba9-46d6-4a24-9b82-5bf67536828f" # Setting this to use workload identity
    keyvaultName: accessapp2vault      # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ExampleSecret             # Set to the name of your secret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: ExampleSecret1                # Set to the name of your key
          objectType: secret
          objectVersion: ""
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"        # The tenant ID of the key vault